### PR TITLE
Version 5.0.0

### PR DESCRIPTION
**Pull request by indiesquidge**

### CODE REVIEW

**Comment by ljharb** [comment]
Before doing this update, let's add the "exports" field :-) i'll push a commit to this PR, one sec

**Comment by ljharb** [comment]
k, bumped the deps and added the exports field. this should be good to go (i ordered the commits so a fast-forward merge should be ideal)

**Review by ljharb — APPROVED** [review]

**Comment by ljharb** [comment]
ok, good to go.

**Comment by ljharb** [comment]
(later, once node 14 fixes its bug, we can revert 31bf4f4)

**Comment by indiesquidge** [comment]
Thanks a bunch for the timely help on all of this @ljharb

**Comment by ljharb** [comment]
np at all. looks like the node issue was a transitory issue with their CDN, so that commit can be reverted. I'll do that in a PR, that also adds some node tests.

**Comment by lencioni** [comment]
Published as https://www.npmjs.com/package/react-with-styles/v/5.0.0

**Pull request merged**
